### ISSUE TITLE
How to use .env variables in dbconf.yml?

### ISSUE THREAD

**Issue by necessarylion** [Altoros/gorm-goose#6]
Example
```yml
development:
  driver: postgres
  open: postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable
```
